<?php
require_once __DIR__.'/../_shared/admin-auth.php';
bp_cors('POST, OPTIONS');$d=bp_json();$actor=bp_require_role($d,['super_admin','content_admin']);
$studentId=(int)($d['student_id']??0);$scheduleId=(int)($d['schedule_id']??0);$subjectId=(int)($d['subject_id']??0);$academicId=isset($d['academic_id'])?(int)$d['academic_id']:null;$title=trim((string)($d['title']??''));$description=trim((string)($d['description']??''));$type=trim((string)($d['material_type']??$d['type']??''));$link=trim((string)($d['material_url']??$d['link']??''));
if($studentId<=0||$scheduleId<=0||$subjectId<=0||$title===''||$description===''||$type===''||$link===''){echo json_encode(['status'=>'error','success'=>false,'message'=>'Required learning material information is missing.']);exit;}
$c=bp_admin_conn();$v=$c->prepare('SELECT schedule_id,academic_id,subject_id FROM study_schedule WHERE schedule_id=? AND student_id=? AND subject_id=? AND date_deleted IS NULL LIMIT 1');$v->bind_param('iii',$scheduleId,$studentId,$subjectId);$v->execute();$sch=$v->get_result()->fetch_assoc();$v->close();if(!$sch){echo json_encode(['status'=>'error','success'=>false,'message'=>'The selected study schedule is invalid.']);$c->close();exit;}if($academicId===null)$academicId=$sch['academic_id']!==null?(int)$sch['academic_id']:null;
$v=$c->prepare('SELECT material_id FROM learning_material WHERE schedule_id=? AND date_deleted IS NULL LIMIT 1');$v->bind_param('i',$scheduleId);$v->execute();$exists=$v->get_result()->fetch_assoc();$v->close();if($exists){echo json_encode(['status'=>'error','success'=>false,'duplicate'=>true,'code'=>'DUPLICATE_MATERIAL','message'=>'A learning material is already assigned to this scheduled lesson.']);$c->close();exit;}
$status='pending';$s=$c->prepare('INSERT INTO learning_material(schedule_id,subject_id,academic_id,title,type,link,difficulty_level,description,admin_id,approval_status) VALUES(?,?,?,?,?,?,NULL,?,?,?)');$s->bind_param('iiissssis',$scheduleId,$subjectId,$academicId,$title,$type,$link,$description,$actor['admin_id'],$status);if(!$s->execute()){echo json_encode(['status'=>'error','success'=>false,'message'=>'Failed to save the learning material.']);$s->close();$c->close();exit;}$id=$c->insert_id;$s->close();bp_log($c,(int)$actor['admin_id'],'Added Learning Material',$title.' submitted for Super Admin approval.');
$c->close();echo json_encode(['status'=>'success','success'=>true,'message'=>'Learning material saved and submitted for approval.','material_id'=>(int)$id,'approval_status'=>'pending']);
